image:
  - Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-ibank.jar -P:profile=test -port=9999 &
  - chmod +x gradlew

build_script:
  - ./gradlew test -Dselenide.headless=true --info